### ISSUE TITLE
code this on C++

### ISSUE THREAD

**Issue by parbati09** [parbati09/Cpp#1]
Given an integer x, return true if x is palindrome integer.

An integer is a palindrome when it reads the same backward as forward.

For example, 121 is a palindrome while 123 is not.
 

Example 1:

Input: x = 121
Output: true
Explanation: 121 reads as 121 from left to right and from right to left.
Example 2:

Input: x = -121
Output: false
Explanation: From left to right, it reads -121. From right to left, it becomes 121-. Therefore it is not a palindrome.
Example 3:

Input: x = 10
Output: false
Explanation: Reads 01 from right to left. Therefore it is not a palindrome.
 

Constraints:

-231 <= x <= 231 - 1

**Comment by AnshumanGoel** [comment]
I have sent a pull request kindly check it
Thank You

**Comment by yashsarnaik22** [comment]
can you please assign this to me?

**Comment by UstitvaG** [comment]
hello, i would like to work on this issue. 
could you assign this issue to me?
